server:
  port: 8082

spring:
  application:
    name: velocity-mall-order
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/velocity_mall_order?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: velocity-mall-order-producer-group
