server:
  port: 8083

spring:
  application:
    name: velocity-mall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/velocity_mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&createDatabaseIfNotExist=true
    username: root
    password: root
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true
    out-of-order: false
    encoding: UTF-8
  data:
    redis:
      host: 127.0.0.1
      port: 6379

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: seckill-producer-group

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-not-delete-value: 0
