server:
  port: 8080

spring:
  application:
    name: velocity-mall-gateway
  main:
    web-application-type: reactive
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      filter:
        enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: product-route
          uri: lb://velocity-mall-product
          predicates:
            - Path=/api/v1/products/**
        - id: category-route
          uri: lb://velocity-mall-product
          predicates:
            - Path=/api/v1/categories/**
        - id: order-route
          uri: lb://velocity-mall-order
          predicates:
            - Path=/api/v1/orders/**
        - id: cart-route
          uri: lb://velocity-mall-order
          predicates:
            - Path=/api/v1/carts/**
        - id: seckill-route
          uri: lb://velocity-mall-seckill
          predicates:
            - Path=/api/v1/seckill/**
        - id: search-route
          uri: lb://velocity-mall-search
          predicates:
            - Path=/api/v1/search/**
        - id: coupon-route
          uri: lb://velocity-mall-coupon
          predicates:
            - Path=/api/v1/coupons/**
        - id: review-route
          uri: lb://velocity-mall-review
          predicates:
            - Path=/api/v1/reviews/**
        - id: user-route
          uri: lb://velocity-mall-user
          predicates:
            - Path=/api/v1/users/**
        - id: admin-route
          uri: lb://velocity-mall-admin
          predicates:
            - Path=/api/v1/admin/**
        - id: minio-route
          uri: http://127.0.0.1:9000
          predicates:
            - Path=/minio/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

jwt:
  secret: 7A2B4C6D8E0F1A3B5C7D9E2F4A6B8C0D7A2B4C6D8E0F1A3B5C7D9E2F4A6B8C0D
